name: Build and Deploy to Docker Hub

on: 
  push: 
    branches: [main]

  pull_request:
    branches: [main]
  
jobs:

  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
      - uses: actions/checkout@v4

      - name: Install Dependency
        uses: bahmutov/npm-install@v1
      
      - name: Testing the suite

        run: npm run test

  publish_images:
    
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: Docker Login
          uses: docker/login-action@v3
          with: 
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_PASS}}
    
        - name: build image
          run: docker build --tag saphalpantha/react-utest:latest -f Dockerfile.dev .

        - name: push image to docker Hub
          run: |
            docker push saphalpantha/serve-node:latest
            
##COMPLETED